# Generated by Django 5.0.4 on 2024-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='todo_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complete_status', models.BooleanField(default=False)),
            ],
        ),
    ]
