# Generated by Django 5.0.4 on 2024-05-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todomodel_date_and_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='date_and_time',
            new_name='due_date_and_time',
        ),
    ]
